// ledger.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: ledger/v1/ledger.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_ledger_v1_ledger_proto protoreflect.FileDescriptor

const file_ledger_v1_ledger_proto_rawDesc = "" +
	"\n" +
	"\x16ledger/v1/ledger.proto\x12\tledger.v1\x1a\x1bledger/v1/transaction.proto\x1a\x17ledger/v1/account.proto2\xe5\x02\n" +
	"\rLedgerService\x12^\n" +
	"\x11CreateTransaction\x12#.ledger.v1.CreateTransactionRequest\x1a$.ledger.v1.CreateTransactionResponse\x12U\n" +
	"\x0eGetTransaction\x12 .ledger.v1.GetTransactionRequest\x1a!.ledger.v1.GetTransactionResponse\x12R\n" +
	"\rCreateAccount\x12\x1f.ledger.v1.CreateAccountRequest\x1a .ledger.v1.CreateAccountResponse\x12I\n" +
	"\n" +
	"GetBalance\x12\x1c.ledger.v1.GetBalanceRequest\x1a\x1d.ledger.v1.GetBalanceResponseBMZKgithub.com/andreis3/isura-ledger-ms/internal/transport/grpc/pb/ledger/v1;pbb\x06proto3"

var file_ledger_v1_ledger_proto_goTypes = []any{
	(*CreateTransactionRequest)(nil),  // 0: ledger.v1.CreateTransactionRequest
	(*GetTransactionRequest)(nil),     // 1: ledger.v1.GetTransactionRequest
	(*CreateAccountRequest)(nil),      // 2: ledger.v1.CreateAccountRequest
	(*GetBalanceRequest)(nil),         // 3: ledger.v1.GetBalanceRequest
	(*CreateTransactionResponse)(nil), // 4: ledger.v1.CreateTransactionResponse
	(*GetTransactionResponse)(nil),    // 5: ledger.v1.GetTransactionResponse
	(*CreateAccountResponse)(nil),     // 6: ledger.v1.CreateAccountResponse
	(*GetBalanceResponse)(nil),        // 7: ledger.v1.GetBalanceResponse
}
var file_ledger_v1_ledger_proto_depIdxs = []int32{
	0, // 0: ledger.v1.LedgerService.CreateTransaction:input_type -> ledger.v1.CreateTransactionRequest
	1, // 1: ledger.v1.LedgerService.GetTransaction:input_type -> ledger.v1.GetTransactionRequest
	2, // 2: ledger.v1.LedgerService.CreateAccount:input_type -> ledger.v1.CreateAccountRequest
	3, // 3: ledger.v1.LedgerService.GetBalance:input_type -> ledger.v1.GetBalanceRequest
	4, // 4: ledger.v1.LedgerService.CreateTransaction:output_type -> ledger.v1.CreateTransactionResponse
	5, // 5: ledger.v1.LedgerService.GetTransaction:output_type -> ledger.v1.GetTransactionResponse
	6, // 6: ledger.v1.LedgerService.CreateAccount:output_type -> ledger.v1.CreateAccountResponse
	7, // 7: ledger.v1.LedgerService.GetBalance:output_type -> ledger.v1.GetBalanceResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ledger_v1_ledger_proto_init() }
func file_ledger_v1_ledger_proto_init() {
	if File_ledger_v1_ledger_proto != nil {
		return
	}
	file_ledger_v1_transaction_proto_init()
	file_ledger_v1_account_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ledger_v1_ledger_proto_rawDesc), len(file_ledger_v1_ledger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ledger_v1_ledger_proto_goTypes,
		DependencyIndexes: file_ledger_v1_ledger_proto_depIdxs,
	}.Build()
	File_ledger_v1_ledger_proto = out.File
	file_ledger_v1_ledger_proto_goTypes = nil
	file_ledger_v1_ledger_proto_depIdxs = nil
}
