services:
  postgres:
    image: postgres:18.3
    container_name: isura-ledger-postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d isura_ledger_main"]
      interval: 5s
      timeout: 2s
      retries: 5
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: isura_ledger_main
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "synchronous_commit=on"]

  nats:
    image: nats:latest
    container_name: isura-ledger-nats
    restart: always
    ports:
      - "4222:4222" # Porta padrão para clientes Go
      - "8222:8222" # Porta de monitoramento HTTP do NATS
    command: [ "-js", "--http_port", "8222" ]

  tempo:
    image: grafana/tempo:2.4.1
    container_name: isura-ledger-tempo
    ports:
      - "3200:3200"  # HTTP
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP ← o ledger envia aqui
    command: [ "--config.file=/etc/tempo.yaml" ]
    volumes:
      - ./docker/tempo/tempo.yaml:/etc/tempo.yaml

  prometheus:
    image: prom/prometheus:latest
    container_name: isura-ledger-prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: isura-ledger-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - tempo

#  ledger:
#    build:
#        context: .
#        dockerfile: Dockerfile.local
#    container_name: isura-ledger-ms
#    volumes:
#      - .:/app  # Monta o código fonte para dentro do container
#    restart: always
#    ports:
#      - "50051:50051"
#      - "8080:8080"
#    depends_on:
#      postgres:
#        condition: service_healthy
#    environment:
#      - USER=ledger
#      - ENV=local
#      - POSTGRES_HOST=isura-ledger-postgres
#      - POSTGRES_PORT=5432
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=admin
#      - POSTGRES_DATABASE=isura-ledger

volumes:
  ledger-data: